# General structure of a ruleset and of rules
<root> ::= [?xml version=%1.0% ?][rulebase]<ruleset>[/rulebase]
<ruleset> ::= <regola>|<regola><ruleset>|<regola><regola><ruleset>|<regola><regola><regola><ruleset>
<regola> ::= [rule]<firstpart><secondpart><thirdpart>[/rule]
<firstpart> ::= [previous_states]<ps_list>[/previous_states]
<secondpart> ::= [preconditions]<pc_list>[/preconditions]
<thirdpart> ::= [actions]<a_list>[/actions]
<ps_list> ::= <ps><ps><ps>
<ps> ::= [prv_state id=%<id_state>% /]
<pc_list> ::= <pc>
<pc> ::= [precond id=%<triplet><triplet><triplet><triplet><triplet><triplet><triplet>% value=%<bool>% /]
<a_list> ::= <azione_cngstate><azione_cngvar>
<azione_cngstate> ::= [act1  type=%1% prob=%<prob>%  nxt_state_id=%<id_state>% /]
<azione_cngvar> ::= [act2  type=%2% prob=%<probability>%  variable_id=%<id_var>% value=%<bool>% /]
# Terminal expansions
<id_state>::=0|1|2|3|4
<triplet>::=0|1|-
<dual>::=0|1
<id_var>::=1|2
<probability>::=0.001|0.005|0.01|0.025|0.05|0.075|0.1|1.0
<prob>::=0.1|0.2|0.5|0.7|1.0
<bool>::=true|false
<prob_init_state>::=0.0|0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0
